Written By: kerrie geil
Original Development Date: Feb 2024
Package Requirements: geopandas pyogrio
Description: subsetting the county boundary shapefile to MS and surrounding states so the file will be smaller

In [1]:
import geopandas as gpd
import pyogrio

In [2]:
data_dir=r'C://Users/kerrie/01_data/boundaries/states_2023/'
orig_dir = 'orig/cb_2023_us_state_500k/'
shapefile='cb_2023_us_state_500k.shp'

states_list = ['FL','GA','SC','NC']

# load and subset county shapefile

In [7]:
states=gpd.read_file(data_dir+orig_dir+shapefile,
                      columns = ['STATEFP','STUSPS','NAME'])

print(states.crs)
states

EPSG:4269

,NAME,STATEFP,STUSPS,geometry
0,New Mexico,35,NM,"POLYGON ((-109.05017 31.48, -109.04984 31.4995..."
1,South Dakota,46,SD,"POLYGON ((-104.05788 44.9976, -104.05078 44.99..."
2,California,06,CA,"MULTIPOLYGON (((-118.60442 33.47855, -118.5987..."
3,Kentucky,21,KY,"MULTIPOLYGON (((-89.40565 36.52816, -89.39868 ..."
4,Alabama,01,AL,"MULTIPOLYGON (((-88.05338 30.50699, -88.05109 ..."
5,Georgia,13,GA,"MULTIPOLYGON (((-81.27939 31.30792, -81.27716 ..."
6,Arkansas,05,AR,"POLYGON ((-94.61792 36.49941, -94.61765 36.499..."
7,Pennsylvania,42,PA,"POLYGON ((-80.51989 40.90666, -80.51963 40.911..."
8,Missouri,29,MO,"POLYGON ((-95.77355 40.5782, -95.76853 40.5833..."
9,Colorado,08,CO,"POLYGON ((-109.06025 38.59933, -109.05954 38.7..."
10,Utah,49,UT,"POLYGON ((-114.05296 37.59278, -114.05247 37.6..."
11,Oklahoma,40,OK,"POLYGON ((-103.00256 36.52659, -103.00219 36.6..."
12,Tennessee,47,TN,"POLYGON ((-90.31045 35.0027, -90.30926 35.0095..."
13,Wyoming,56,WY,"POLYGON ((-111.05456 45.00096, -111.04507 45.0..."
14,New York,36,NY,"MULTIPOLYGON (((-72.0377 41.25128, -72.03472 4..."
15,Indiana,18,IN,"POLYGON ((-88.09776 37.90403, -88.09448 37.905..."
16,Kansas,20,KS,"POLYGON ((-102.05174 40.00308, -101.9167 40.00..."
17,Idaho,16,ID,"POLYGON ((-117.24268 44.39655, -117.23484 44.3..."
18,Alaska,02,AK,"MULTIPOLYGON (((-131.61758 54.94795, -131.6107..."
19,Nevada,32,NV,"POLYGON ((-120.00645 39.27288, -120.00643 39.2..."
20,Illinois,17,IL,"POLYGON ((-91.51297 40.18106, -91.51107 40.188..."
21,Vermont,50,VT,"POLYGON ((-73.43774 44.04501, -73.43199 44.063..."
22,Minnesota,27,MN,"MULTIPOLYGON (((-89.59206 47.96668, -89.59147 ..."
23,Iowa,19,IA,"POLYGON ((-96.63836 42.7355, -96.63797 42.7363..."
24,South Carolina,45,SC,"MULTIPOLYGON (((-79.50795 33.02008, -79.50713 ..."
25,New Hampshire,33,NH,"MULTIPOLYGON (((-70.61702 42.97718, -70.61529 ..."
26,Delaware,10,DE,"MULTIPOLYGON (((-75.56752 39.5102, -75.56477 3..."
27,District of Columbia,11,DC,"POLYGON ((-77.11976 38.93434, -77.11253 38.940..."
28,American Samoa,60,AS,"MULTIPOLYGON (((-168.14582 -14.54791, -168.145..."
29,Connecticut,09,CT,"MULTIPOLYGON (((-72.22593 41.29384, -72.22523 ..."
30,Michigan,26,MI,"MULTIPOLYGON (((-83.19159 42.03537, -83.18993 ..."
31,Massachusetts,25,MA,"MULTIPOLYGON (((-70.23405 41.28565, -70.22122 ..."
32,Florida,12,FL,"MULTIPOLYGON (((-80.17628 25.52505, -80.17395 ..."
33,United States Virgin Islands,78,VI,"MULTIPOLYGON (((-64.62765 17.78857, -64.62727 ..."
34,New Jersey,34,NJ,"MULTIPOLYGON (((-74.0422 40.69997, -74.039 40...."
35,North Dakota,38,ND,"POLYGON ((-104.04868 48.86378, -104.04865 48.8..."
36,Maryland,24,MD,"MULTIPOLYGON (((-76.04998 37.99011, -76.04865 ..."
37,Maine,23,ME,"MULTIPOLYGON (((-67.3226 44.6116, -67.32174 44..."
38,Hawaii,15,HI,"MULTIPOLYGON (((-156.06076 19.73055, -156.0566..."
39,Guam,66,GU,"MULTIPOLYGON (((144.64538 13.23627, 144.64764 ..."
40,Commonwealth of the Northern Mariana Islands,69,MP,"MULTIPOLYGON (((145.6327 16.36647, 145.63295 1..."
41,Rhode Island,44,RI,"MULTIPOLYGON (((-71.28802 41.64558, -71.28647 ..."
42,Montana,30,MT,"POLYGON ((-116.04914 48.50205, -116.04913 48.5..."
43,Arizona,04,AZ,"POLYGON ((-114.81629 32.50804, -114.81432 32.5..."
44,Nebraska,31,NE,"POLYGON ((-104.05342 41.17054, -104.05321 41.1..."
45,Washington,53,WA,"MULTIPOLYGON (((-122.33164 48.02056, -122.3283..."
46,Puerto Rico,72,PR,"MULTIPOLYGON (((-65.23773 18.32118, -65.23612 ..."
47,Texas,48,TX,"MULTIPOLYGON (((-94.7183 29.72886, -94.71721 2..."
48,Ohio,39,OH,"MULTIPOLYGON (((-82.73447 41.60351, -82.72425 ..."
49,Wisconsin,55,WI,"MULTIPOLYGON (((-86.8309 45.42602, -86.82866 4..."
50,Oregon,41,OR,"MULTIPOLYGON (((-123.66475 46.24431, -123.6489..."
51,Mississippi,28,MS,"MULTIPOLYGON (((-88.50502 30.21574, -88.49164 ..."
52,North Carolina,37,NC,"MULTIPOLYGON (((-75.72681 35.93584, -75.71827 ..."
53,Virginia,51,VA,"MULTIPOLYGON (((-75.74241 37.80835, -75.74151 ..."
54,West Virginia,54,WV,"POLYGON ((-82.6432 38.16909, -82.643 38.16956,..."
55,Louisiana,22,LA,"MULTIPOLYGON (((-88.8677 29.86155, -88.86566 2..."

In [8]:
states.dtypes

NAME          object
STATEFP       object
STUSPS        object
geometry    geometry
dtype: object

In [9]:
states = states.loc[states.STUSPS.isin(states_list)].reset_index(drop=True)
states

,NAME,STATEFP,STUSPS,geometry
0,Georgia,13,GA,"MULTIPOLYGON (((-81.27939 31.30792, -81.27716 ..."
1,South Carolina,45,SC,"MULTIPOLYGON (((-79.50795 33.02008, -79.50713 ..."
2,Florida,12,FL,"MULTIPOLYGON (((-80.17628 25.52505, -80.17395 ..."
3,North Carolina,37,NC,"MULTIPOLYGON (((-75.72681 35.93584, -75.71827 ..."

# write to new shapefile

In [10]:
states.to_file(data_dir+'FL_GA_SC_NC/FL_GA_SC_NC_cb_2023_us_state_500k.shp')