Written By: kerrie geil
Original Development Date: Feb 2025
Package Requirements: 
Description: removing unnecessary columns from GBIF data to make file smaller

In [1]:
import pandas as pd

In [7]:
data_dir=r'C://Users/kerrie/01_data/GBIF/redEaredSliders/'
data_file = '0000795-250218110819086.csv'

out_dir = r'C://Users/kerrie/00_code/repos/DEV_canvas_beginner_py/data/GBIF/'
out_file = 'redEaredSliders_iNaturalist_GBIF_USsouth_2015-2024.csv'

# load and subset

In [3]:
# preview layer data in a geodataframe
df = pd.read_csv(data_dir+data_file, sep ='\t')#, 
                 # usecols=['verbatimScientificName','stateProvince','decimalLatitude',
                 #          'decimalLongitude','coordinateUncertaintyInMeters','eventDate'])
df.head()

,gbifID,datasetKey,occurrenceID,kingdom,phylum,class,order,family,genus,species,...,identifiedBy,dateIdentified,license,rightsHolder,recordedBy,typeStatus,establishmentMeans,lastInterpreted,mediaType,issue
0,5064128588,50c9509d-22c7-4a22-a47d-8c48425ef4a7,https://www.inaturalist.org/observations/26130...,Animalia,Chordata,Testudines,NaN,Emydidae,Trachemys,Trachemys scripta,...,pisum,2025-02-11T01:55:22,CC_BY_NC_4_0,pisum,pisum,NaN,NaN,2025-02-16T15:58:43.475Z,StillImage,COORDINATE_ROUNDED;CONTINENT_DERIVED_FROM_COOR...
1,5064097434,50c9509d-22c7-4a22-a47d-8c48425ef4a7,https://www.inaturalist.org/observations/26129...,Animalia,Chordata,Testudines,NaN,Emydidae,Trachemys,Trachemys scripta,...,junomoon,2025-02-11T03:15:18,CC_BY_NC_4_0,Mary,Mary,NaN,NaN,2025-02-16T15:58:43.074Z,StillImage,COORDINATE_ROUNDED;CONTINENT_DERIVED_FROM_COOR...
2,5064093865,50c9509d-22c7-4a22-a47d-8c48425ef4a7,https://www.inaturalist.org/observations/26129...,Animalia,Chordata,Testudines,NaN,Emydidae,Trachemys,Trachemys scripta,...,Mary,2025-02-11T00:36:38,CC_BY_NC_4_0,Mary,Mary,NaN,NaN,2025-02-16T15:58:43.712Z,StillImage,COORDINATE_ROUNDED;CONTINENT_DERIVED_FROM_COOR...
3,5064077884,50c9509d-22c7-4a22-a47d-8c48425ef4a7,https://www.inaturalist.org/observations/26137...,Animalia,Chordata,Testudines,NaN,Emydidae,Trachemys,Trachemys scripta,...,pisum,2025-02-11T19:16:55,CC_BY_NC_4_0,pisum,pisum,NaN,NaN,2025-02-16T15:58:48.070Z,StillImage,COORDINATE_ROUNDED;CONTINENT_DERIVED_FROM_COOR...
4,5063941995,50c9509d-22c7-4a22-a47d-8c48425ef4a7,https://www.inaturalist.org/observations/26095...,Animalia,Chordata,Testudines,NaN,Emydidae,Trachemys,Trachemys scripta,...,Matthew,2025-02-08T02:41:03,CC_BY_NC_4_0,czimmer3,czimmer3,NaN,NaN,2025-02-16T15:58:21.547Z,StillImage,COORDINATE_ROUNDED;CONTINENT_DERIVED_FROM_COOR...

In [4]:
# see all column names
df.columns.tolist()

['gbifID',
 'datasetKey',
 'occurrenceID',
 'kingdom',
 'phylum',
 'class',
 'order',
 'family',
 'genus',
 'species',
 'infraspecificEpithet',
 'taxonRank',
 'scientificName',
 'verbatimScientificName',
 'verbatimScientificNameAuthorship',
 'countryCode',
 'locality',
 'stateProvince',
 'occurrenceStatus',
 'individualCount',
 'publishingOrgKey',
 'decimalLatitude',
 'decimalLongitude',
 'coordinateUncertaintyInMeters',
 'coordinatePrecision',
 'elevation',
 'elevationAccuracy',
 'depth',
 'depthAccuracy',
 'eventDate',
 'day',
 'month',
 'year',
 'taxonKey',
 'speciesKey',
 'basisOfRecord',
 'institutionCode',
 'collectionCode',
 'catalogNumber',
 'recordNumber',
 'identifiedBy',
 'dateIdentified',
 'license',
 'rightsHolder',
 'recordedBy',
 'typeStatus',
 'establishmentMeans',
 'lastInterpreted',
 'mediaType',
 'issue']

In [5]:
# finding which field has the scientific name
df.loc[0,['scientificName','verbatimScientificName','verbatimScientificNameAuthorship']]

scientificName                      Trachemys scripta elegans (Wied, 1838)
verbatimScientificName                           Trachemys scripta elegans
verbatimScientificNameAuthorship                                       NaN
Name: 0, dtype: object

In [9]:
# subset columns

# subset columns 
df = pd.read_csv(data_dir+data_file, sep ='\t', 
                 usecols=['verbatimScientificName','stateProvince','decimalLatitude',
                          'decimalLongitude','coordinateUncertaintyInMeters','eventDate'])
df.head()

,verbatimScientificName,stateProvince,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,eventDate
0,Trachemys scripta elegans,Texas,29.764617,-95.453697,10.0,2024-09-04T16:00
1,Trachemys scripta elegans,Texas,28.983560,-96.012085,228.0,2024-11-09T11:04
2,Trachemys scripta elegans,Texas,28.983560,-96.012085,228.0,2024-11-09T11:05
3,Trachemys scripta elegans,Texas,29.764506,-95.453683,15.0,2024-09-13T13:27
4,Trachemys scripta elegans,Texas,32.317042,-95.252815,1078.0,2024-09-09T12:02:54

# write file

In [12]:
df.to_csv(out_dir+out_file, index = None, header=True)