Written By: kerrie geil
Original Development Date: Feb 2024
Package Requirements: fiona, geopandas, shapely
Description: subsetting the county boundary shapefile to MS and surrounding states so the file will be smaller

In [3]:
# import fiona
import geopandas as gpd
import pyogrio
# import shapely
# import os
# os.environ['GDAL_DATA'] = os.environ['CONDA_PREFIX'] + r'/Library/share/gdal'
# os.environ['PROJ_LIB'] = os.environ['CONDA_PREFIX'] + r'/Library/share'

In [12]:
data_dir=r'C://Users/kerrie/Documents/02_LocalData/boundaries/'
shapefile='tl_2020_us_county.shp'

states_list = ['MS','LA','AR','AL','TN'] 
# https://www.bls.gov/respondents/mwr/electronic-data-interchange/appendix-d-usps-state-abbreviations-and-fips-codes.htm
statefp_list = ['28','22','05','01','47']

# load and subset county shapefile

In [10]:
counties=gpd.read_file(data_dir+'orig/counties_2020/'+shapefile,
                      columns = ['STATEFP','COUNTYFP','NAME'])

print(counties.crs)
counties

EPSG:4269

,COUNTYFP,NAME,STATEFP,geometry
0,039,Cuming,31,"POLYGON ((-97.01952 42.0041, -97.01952 42.0049..."
1,069,Wahkiakum,53,"POLYGON ((-123.43639 46.2382, -123.44759 46.24..."
2,011,De Baca,35,"POLYGON ((-104.56739 33.99757, -104.56772 33.9..."
3,109,Lancaster,31,"POLYGON ((-96.91075 40.78494, -96.91075 40.790..."
4,129,Nuckolls,31,"POLYGON ((-98.27367 40.0894, -98.27367 40.0894..."
...,...,...,...,...
3229,123,Gilmer,13,"POLYGON ((-84.65478 34.66559, -84.65488 34.669..."
3230,135,Roseau,27,"POLYGON ((-96.40466 48.80528, -96.40467 48.813..."
3231,089,Madison,28,"POLYGON ((-90.09362 32.70763, -90.0936 32.7076..."
3232,227,Howard,48,"POLYGON ((-101.69227 32.27106, -101.69221 32.2..."
3233,099,Wayne,54,"POLYGON ((-82.59529 38.36978, -82.59515 38.369..."

In [11]:
counties.dtypes

COUNTYFP      object
NAME          object
STATEFP       object
geometry    geometry
dtype: object

In [14]:
counties = counties.loc[counties.STATEFP.isin(statefp_list)].reset_index(drop=True)
counties

,COUNTYFP,NAME,STATEFP,geometry
0,027,Clay,01,"POLYGON ((-85.97879 33.32757, -85.97876 33.328..."
1,137,Stone,05,"POLYGON ((-92.41528 35.86091, -92.41513 35.866..."
2,061,Jasper,28,"POLYGON ((-89.32183 31.96321, -89.32182 31.964..."
3,065,Hamilton,47,"POLYGON ((-85.29254 35.26291, -85.29238 35.263..."
4,091,Marengo,01,"POLYGON ((-87.9297 32.29252, -87.9318 32.29727..."
...,...,...,...,...
378,101,Lewis,47,"POLYGON ((-87.6578 35.56068, -87.65779 35.5607..."
379,041,Franklin,22,"POLYGON ((-91.8006 32.22356, -91.80028 32.2235..."
380,155,Webster,28,"POLYGON ((-89.22905 33.72189, -89.2253 33.7219..."
381,057,Hempstead,05,"POLYGON ((-93.82865 33.83442, -93.82862 33.835..."
382,089,Madison,28,"POLYGON ((-90.09362 32.70763, -90.0936 32.7076..."

# write to new shapefile

In [15]:
counties.to_file(data_dir+'tl_2020_us_county_subset.shp')

In [ ]:
# write the study area shape to a new shapefile
schema={'geometry':study_area.geom_type,
        'properties':{'id':'int'}}

with fiona.open(data_dir+'MS_bounds.shp','w','ESRI Shapefile',schema,crs=fiona.crs.from_epsg(4326)) as f:
    f.write({'geometry':shapely.geometry.mapping(study_area),'properties':{'id':0}})

In [ ]:
test=gpd.read_file(data_dir+'MS_bounds.shp')#,layer=layers[0])
test

In [ ]:
test.plot()

In [ ]:
print(test.crs)

# write rectangular bounding box to shapefile

for crude subsetting of large data files

In [ ]:
boundbox = study_area.envelope
print(boundbox.geom_type)
boundbox

In [ ]:
# write to new shapefile
schema={'geometry':'Polygon',
        'properties':{'id':'int'}}

with fiona.open(data_dir+'study_area_bounding_box.shp','w','ESRI Shapefile',schema,crs=fiona.crs.from_epsg(4326)) as f:
    f.write({'geometry':shapely.geometry.mapping(boundbox),'properties':{'id':0}})